"""
Django settings for women_clothing_shop project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-lal2*49rg(q_kn=nu%+w+(7jbi7wwsy15rq4l(m*_-lhh^g3*0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third-party app: Adds template filters like 'intcomma'
    # for formatting numbers (e.g., 1,234,567).
    'django.contrib.humanize',
]

# Local apps
INSTALLED_APPS += [
    "accounts",
    "core",
    "shop",
    "purchase",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Manages user sessions (e.g., for the shopping cart)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # Adds the 'request.user' object to requests
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Enables the 'messages' framework for notifications
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "women_clothing_shop.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Tells Django to look in the project-level 'templates'
        # directory for base templates (e.g., base.html).
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,  # Tells Django to look inside app directories (e.g., 'core/templates/')
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # --- Your Custom Context Processors ---
                # Makes '{{ cart }}' available on *every* page
                'core.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = "women_clothing_shop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fa'  # Set to Persian
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True  # Enable internationalization
USE_L10N = True  # Enable localization (e.g., date formatting)
USE_THOUSAND_SEPARATOR = True  # Enables thousand separators for numbers

USE_TZ = True  # Enable timezone-aware datetimes


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Tells Django where to find *your* project-level static files
# (e.g., global CSS, JS, images)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# The *output* directory for 'collectstatic' in production.
# Django will copy all static files (from apps and STATICFILES_DIRS) here.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Your Custom Project Settings ---

# CRITICAL: Tells Django to use your 'core.CustomUser' model
# for all authentication, not the default User model.
AUTH_USER_MODEL = 'accounts.CustomUser'

# --- Media Files (User-Uploaded Content) ---
# The base URL to access user-uploaded files in the browser
MEDIA_URL = '/media/'
# The physical directory on the server where uploaded files will be stored
# (e.g., product images, profile pictures)
MEDIA_ROOT = BASE_DIR / 'media'

# Defines the session key used by your 'core.cart.Cart' class
CART_SESSION_ID = 'cart'